name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Dotnet Restore
      run: dotnet restore ./Api

    - name: Dotnet Build
      run: dotnet build ./Api -c Release --no-restore
      
    - name: Run Unit Tests
      run: dotnet test ./Api --filter FullyQualifiedName~UnitTests

    - name: Run Integration Tests
      run: dotnet test ./Api --filter FullyQualifiedName~IntegrationTests

    - name: Dotnet publish
      run: dotnet publish -c Release ./Api --no-restore --no-build
      
    - name: Bump version and push tag
      if: github.event.pull_request.merged == false
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
        PRERELEASE: true
        PRERELEASE_SUFFIX: pr-${{ github.event.pull_request.number }}

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: tudoranghelina91
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Back-End Docker image
      run: docker build ./Api --tag ghcr.io/tudoranghelina91/pwpa-call-logging-pwpa_call_logging_api:latest
    - name: Push Back-End Docker image
      run: docker push ghcr.io/tudoranghelina91/pwpa-call-logging-pwpa_call_logging_api:latest
      
    - name: Build Front-End Docker image
      run: docker build ./FrontEnd --tag ghcr.io/tudoranghelina91/pwpa-call-logging-pwpa_call_logging_frontend:latest
    - name: Push Front-End Docker image
      run: docker push ghcr.io/tudoranghelina91/pwpa-call-logging-pwpa_call_logging_frontend:latest
